collections:
  - austria:
      output: true
      permalink: /austria/:path/
  - world:
      output: true
      permalink: /world/:path/
  - sustainability:
      output: true
      permalink: /sustainability/:path/
